EXP_NAME: dataset_domain_I3D

DATA:
  type: all_type_videos
  train_data_name: ff
  train_data_path: /root/datasets/ff
  test_data_name: dfdc
  test_data_path: /root/volume1/dfdc_preprocessed
  image_size: 224
  batch_size: 16
  crop_ratio: 1
  num_workers: 4
  frame_num: 32 # for video

MODEL:
  name: I3D
  pretrained: True
  num_classes: 2

TRAIN:
  epochs: 10
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 10
  save_interval: 100
  load_ckpt_dir: None
